In [801]:
# Roba a caso su pytorch
from torch import nn
import torch
import numpy as np

In [802]:
model = nn.Sequential(
    nn.Linear(1,1)
)

with torch.no_grad():
    for p in model.parameters():
        print(p)

Parameter containing:
tensor([[-0.8549]], requires_grad=True)
Parameter containing:
tensor([-0.6834], requires_grad=True)


In [803]:
x = torch.tensor([2], dtype=torch.float32)

In [814]:
model(x).detach().numpy()

array([-2.3931856], dtype=float32)

In [805]:
model.zero_grad()

In [806]:
loss_fun = nn.MSELoss()
loss = loss_fun(torch.tensor([2.0]), model(x)+1)

In [807]:
loss.backward()
print(loss)

tensor(11.5137, grad_fn=<MseLossBackward0>)


In [808]:
with torch.no_grad():
    for p in model.parameters():
        print(p.grad)

tensor([[-13.5727]])
tensor([-6.7864])
